/**
 * Shared types for Hub ManIAcos.
 * Database types generated by Supabase CLI will go in src/lib/database.types.ts (T003).
 */

export type MemberStatus = 'active' | 'idle' | 'away'

export type MemberName = 'Franco' | 'Lucho' | 'Noe'

export interface TeamStatus {
  id: string
  member_email: string
  member_name: MemberName
  current_project: string | null
  current_task: string | null
  status: MemberStatus
  last_active_at: string
  updated_at: string
}

export type ProjectStatus = 'active' | 'paused' | 'done'

export interface Client {
  id: string
  slug: string
  name: string
  description: string | null
  contact_info: Record<string, string> | null
  notes_md: string | null
  created_at: string
  updated_at: string
}

export interface Project {
  id: string
  name: string
  client_name: string
  client_id: string | null
  description: string | null
  notes_md: string | null
  status: ProjectStatus
  vercel_url: string | null
  github_url: string | null
  server_path: string | null  // /srv/maniacos/<slug> on Oracle — null = terminal disabled
  owner_email: string
  created_at: string
  updated_at: string
}

export interface McpConfig {
  id: string
  project_id: string
  mcp_name: string
  config: Record<string, string>
  created_at: string
  updated_at: string
}

export type AgentRunStatus = 'success' | 'error' | 'override' | 'blocked'

export interface AgentRun {
  id: string
  agent_name: string | null
  input_tokens: number | null
  output_tokens: number | null
  model: string | null
  cost_usd: number | null
  status: AgentRunStatus
  human_approved_by: string | null
  input_payload: Record<string, unknown> | null
  output_payload: Record<string, unknown> | null
  error_msg: string | null
  created_at: string
}

export interface Note {
  id: string
  title: string
  content_md: string
  client_id: string | null
  project_id: string | null
  created_by: string
  created_at: string
  updated_at: string
}

export type ClientResourceKind = 'note' | 'diagram' | 'file' | 'conversation'

export interface ClientResource {
  id: string
  client_id: string
  kind: ClientResourceKind
  title: string
  content: Record<string, unknown> | null  // {html:"..."} for notes, excalidraw json for diagrams
  file_url: string | null
  created_by: string
  created_at: string
  updated_at: string
}

// ── Marketing ─────────────────────────────────────────────────────────────────

export type CampaignStatus = 'draft' | 'active' | 'paused' | 'closed'
export type CampaignChannel = 'whatsapp' | 'email' | 'both'

export interface Campaign {
  id: string
  name: string
  icp_prompt: string
  channel: CampaignChannel
  owner_email: string
  status: CampaignStatus
  created_at: string
  updated_at: string
}

export type LeadStatus = 'raw' | 'enriched' | 'approved' | 'sent' | 'replied' | 'closed' | 'rejected'

export interface EnrichedData {
  contact_name?: string | null
  linkedin?: string | null
  bio?: string | null
  fit_score?: number | null
  fit_reason?: string | null
}

export interface Lead {
  id: string
  campaign_id: string
  company: string
  industry: string | null
  city: string | null
  website: string | null
  phone: string | null
  email: string | null
  source: string
  place_id: string | null
  raw_data: Record<string, unknown> | null
  status: LeadStatus
  fit_score: number | null
  enriched_data: EnrichedData | null
  enrichment_error: string | null
  enriched_at: string | null
  created_at: string
}

// Panel nav items
export interface NavItem {
  id: string
  label: string
  href: string
  icon: string  // lucide icon name
}
